# ==============================================================================
#
#          FILE: deploy.yml
#
#         USAGE: called on push
#
#   DESCRIPTION: This workflow runs a script that builds the web application and
#                adds the latex templates. The application is created in a
#                temporary directory and then pushed to the remote repository.
#
#       OPTIONS: see section 'env'
#
#  REQUIREMENTS: A key pair is needed to push to the remote repository. The
#                private key needs to be added as an *actions secret* named
#                'ID_RSA' to this repository. The public key needs to be added
#                as a *deploy key* to the remote repository; the option *allow
#                write access* must be enabled.
#
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Fabian Eberts
#  ORGANIZATION: ---
#       CREATED: ---
#      REVISION: ---
#
# ==============================================================================

name: Build and deploy 
on: [push]
jobs:
  Publish-Templates:
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO: "fhswf/LaTeX-Editor"
      REMOTE_CUSTOM_URL: "" # optional, leave empty ("") if not needed
    steps:
      - name: Check out this repo (templates)
        uses: actions/checkout@v3
        with:
          path: this_repo
      - name: Check out remote repo (web application)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REMOTE_REPO }}
          path: remote_repo
      - name: Build web application
        run: |
          mkdir ${{ github.workspace }}/new_website/
          cd ${{ github.workspace }}/this_repo
          ./build.sh "${{ github.workspace }}/new_website/" "$REMOTE_REPO" "$REMOTE_CUSTOM_URL"
      - name: Add files to remote repo
        run: |
          cd ${{ github.workspace }}/remote_repo
          git rm -r .
          cp -r ${{ github.workspace }}/new_website/* .
          git add .
      - name: Set up SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
      - name: Commit and push to remote repo
        run: |
          cd ${{ github.workspace }}/remote_repo
          git remote set-url origin "git@github.com:${REMOTE_REPO}.git"
          git config user.name "github-actions"
          git config user.email "noreply"
          git commit --allow-empty -am "update"
          git push
